### PR TITLE
biomass check [fix #2]

### LINKED ISSUE #2: Test that the sum of molecular masses of biomass precursors adds up to 1 g DCW

### PR DESCRIPTION
**Pull request by ChristianLieven**
Add checks and tests that assert the sum of biomass components to be 1 within an absolute deviation of 1e-03.

### CODE REVIEW

**Comment by Midnighter** [comment]
@ChristianLieven and I were just talking about that yesterday. We clearly need to distinguish them but haven't had a really complete answer yet. Do you have a suggestion for a good approach?

**Comment by beatrizgj** [comment]
I understand a biomass component reaction is a normal reaction, with left and right sides; while the main biomass reaction has only one side. It could be useful to distinguish them.

About the independent biomass tests, at least, 'test_biomass_consistency' I think it is only recommendable for main biomass reaction. Maybe the same for some others.

**Comment by beatrizgj** [comment]
Other option is to remove the individual biomass reactions, simplifying to only the main biomass reaction(s) (one side reaction), replacing the biomass component metabolite in main biomass reaction with left hand side of individual component reactions.
Then, the biomass test would be only required for the wild type (and core, if there is) biomass reaction.

**Comment by ChristianLieven** [comment]
> main biomass reaction has only one side
Note that this is not the case when you consider that the biomass reaction should contain a term for growth-associated maintenance. This will lead to the righthand side of the reaction containing the righthand components of an ATP hydrolysis reaction = 'atp + h2o <-> adp + pi + h'

> replacing the biomass component metabolite in main biomass reaction with left hand side of individual component reactions
This would require us to recalculate the stoichiometry of each of the components according to the overall composition.

I recognise how difficult it is to come up with a solution that accepts all possible forms of implementations.

**Comment by beatrizgj** [comment]
I see, it is difficult to find a solution fits all current models,

**Pull request merged**
